<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE documentos [
<!ELEMENT documentos (libros,revistas,periodicos)>
<!ELEMENT libros (libro+)>
<!ELEMENT revistas (revista+)>
<!ELEMENT periodicos (periodico+)>

<!-- elementos de libro-->
<!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>

<!-- Definimos los atributos de libro-->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>
<!ATTLIST libro pag_lib CDATA #IMPLIED>

<!-- capitulo tiene atributos-->
<!ATTLIST capitulo nro CDATA #IMPLIED>
<!ATTLIST capitulo pag_cap CDATA #IMPLIED>
<!-- capitulo tiene elementos-->
<!ELEMENT capitulo (titulo_cap, contenido)>
<!ELEMENT titulo_cap (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!-- contenido tiene un atributo-->
<!ATTLIST contenido url CDATA #IMPLIED>
<!-- mÃ¡s elementos de libro-->
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>





<!-- Definimos los atributos de revista-->
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST revista pag_rev CDATA #IMPLIED>
<!-- elementos de revista-->
<!ELEMENT revista (titulo_rev, numero, indice_rev, secciones)>
<!ELEMENT titulo_rev (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT indice_rev (#PCDATA)>
<!ELEMENT secciones (seccion+)>
<!-- seccion tiene atributos-->
<!ATTLIST seccion pag_sec CDATA #IMPLIED>
<!-- seccion tiene elementos-->
<!ELEMENT seccion (contenido_rev)>
<!ELEMENT contenido_rev (#PCDATA)>
<!-- contenido tiene un atributo-->
<!ATTLIST contenido_rev url CDATA #IMPLIED>




<!-- Definimos los atributos de periodico-->
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacionales | internacionales) #REQUIRED>
<!ATTLIST periodico fech_pub CDATA #IMPLIED>
<!-- elementos de periodico-->
<!ELEMENT periodico (secciones_per, indice_per)>
<!ELEMENT secciones_per (seccion_per+)>
<!ELEMENT indice_per (#PCDATA)>
<!-- seccion tiene atributos-->
<!ATTLIST seccion_per tipo (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!-- seccion tiene elementos-->
<!ELEMENT seccion_per (articulos)>
<!ELEMENT articulos (articulo+)>
<!-- articulo tiene un atributo-->
<!ATTLIST articulo autor CDATA #IMPLIED>
<!-- articulo tiene un elemento-->
<!ELEMENT articulo (contenido_per)>
<!ELEMENT contenido_per (#PCDATA)>
<!-- contenido tiene un atributo-->
<!ATTLIST contenido_per nombre CDATA #IMPLIED>


]>

<documentos>
    <libros>
        <libro id="L0001" tipo_clase="novela" pag_lib="250">
            <titulo>El verano llego</titulo>
            <capitulos>
                <capitulo nro="uno" pag_cap="25">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="dos" pag_cap="35">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="tres" pag_cap="22">
                     <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
        <libro id="L0002" tipo_clase="infantil" pag_lib="250">
            <titulo></titulo>
            <capitulos>
                <capitulo nro="uno" pag_cap="25">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="dos" pag_cap="35">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="tres" pag_cap="22">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
            <libro id="L0003" tipo_clase="didactico" pag_lib="250">
            <titulo></titulo>
            <capitulos>
                <capitulo nro="uno" pag_cap="25">
                     <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="dos" pag_cap="35">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
                <capitulo nro="tres" pag_cap="22">
                    <titulo_cap></titulo_cap>
                    <contenido url="#"></contenido>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
    </libros>

    <revistas>
        <revista id="R0001" tipo_clase="informatica" pag_rev="60">
            <titulo_rev></titulo_rev>
            <numero></numero>
            <indice_rev></indice_rev>
            <secciones>
                <seccion pag_sec="10">
                    <contenido_rev url="#"></contenido_rev>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="corazon" pag_rev="60">
            <titulo_rev></titulo_rev>
            <numero></numero>
            <indice_rev></indice_rev>
            <secciones>
                <seccion pag_sec="10">
                    <contenido_rev url="#"></contenido_rev>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0003" tipo_clase="coches" pag_rev="60">
            <titulo_rev></titulo_rev>
            <numero></numero>
            <indice_rev></indice_rev>
            <secciones>
                <seccion pag_sec="10">
                    <contenido_rev url="#"></contenido_rev>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0004" tipo_clase="investigacion" pag_rev="60">
            <titulo_rev></titulo_rev>
            <numero></numero>
            <indice_rev></indice_rev>
            <secciones>
                <seccion pag_sec="10">
                    <contenido_rev url="#"></contenido_rev>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0005" tipo_clase="otras" pag_rev="60">
            <titulo_rev></titulo_rev>
            <numero></numero>
            <indice_rev></indice_rev>
            <secciones>
                <seccion pag_sec="10">
                    <contenido_rev url="#"></contenido_rev>
                </seccion>
            </secciones>
        </revista>
    </revistas>

    <periodicos>
        <periodico id="P0001" tipo_clase="nacionales" fech_pub="01/05/23">
            <secciones_per>
                <seccion_per tipo="economica">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="opinion">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="deportes">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="nacional">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="internacional">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
            </secciones_per>
            <indice_per></indice_per>
        </periodico>
        <periodico id="P0002" tipo_clase="internacionales" fech_pub="01/05/23">
            <secciones_per>
                <seccion_per tipo="economica">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="opinion">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="deportes">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="nacional">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
                <seccion_per tipo="internacional">
                    <articulos>
                        <articulo autor="">
                            <contenido_per nombre=""></contenido_per>
                        </articulo> 
                    </articulos>
                </seccion_per>
            </secciones_per>
            <indice_per></indice_per>
        </periodico>

    </periodicos>


</documentos>
